### ISSUE TITLE
ACPL_LooseHelmet: optimize ACPL_LooseHelmet_fnc_NeedToPickUp

### ISSUE THREAD

**Issue by kuloodporny** [RomanPL79/ACPL_MM_Systems#11]
https://github.com/RomanPL79/ACPL_MM_Systems/blob/master/ACPL_LooseHelmet/FSMS/fn_PickUp.fsm

Check early exits in conditions, so that expensive conditions are not evaluated frequently.
Check for consciousness, not just being alive

**Comment by RomanPL79** [comment]
PickUp.fms has been reworked, improved version of NeedToPickUp has been also implemented
