### ISSUE TITLE
ACPL_LooseHelmet: Scope fn_Destroyed properly

### ISSUE THREAD

**Issue by kuloodporny** [RomanPL79/ACPL_MM_Systems#14]
https://github.com/RomanPL79/ACPL_MM_Systems/blob/master/ACPL_LooseHelmet/functions/fn_Destroyed.sqf

This function is confusing. The name suggests that this is getter, but this is actually simulation effect, so it should actually be called Destroy or SetDestroyed - then we could fix the item using the same function; we probably won't need to, but that's the "civilized" way to do it.
The randomness check should be removed from the function and decided prior to calling the function.
`if (random 100 < probability) then {params call ACPL_LooseHelmet_Destroy}`

**Comment by RomanPL79** [comment]
Done, name has been changed to fn_destroy. There was also added value for enabling/disabling the effect.

Function from now is not checking that object should be destroyed.
