### ISSUE TITLE
ACPL_SkillSystem_Excluded: handle as object variable rather than array of excluded units

### ISSUE THREAD

**Issue by kuloodporny** [RomanPL79/ACPL_MM_Systems#5]
https://github.com/RomanPL79/ACPL_MM_Systems/blob/master/ACPL_SkillSystem/functions/fn_SetSkill.sqf
Current code related to ACPL_SkillSystem_Excluded and setting skills has O(N) complexity - the more units are excluded, the more computation power it takes to process each unit individually.

If we set variable to units that we want to exclude instead, we will reduce its complexity to O(1).
`if (_unit getVariable ["ACPL_SkillSystem_Excluded", false]) exitWith {};`

For backwards compatiblity, the module's init script should process the global `ACPL_SkillSystem_Excluded` array when processing the module changes:
`{_x setVariable ["ACPL_SkillSystem_Excluded", nil]} forEach allUnits; {_x setVariable ["ACPL_SkillSystem_Excluded", true]} forEach ACPL_SkillSystem_Excluded`
If `ACPL_SkillSystem_Excluded` is public, then this code snippet may be executed on each PC locally, without spamming network for each unit excluded.

**Comment by kuloodporny** [comment]
The method I described above will also make it redundant to check for excluded units in https://github.com/RomanPL79/ACPL_MM_Systems/blob/master/ACPL_SkillSystem/functions/fn_ReloadAll.sqf

**Comment by kuloodporny** [comment]
The same issue is present in ACPL_LooseHelmet
https://github.com/RomanPL79/ACPL_MM_Systems/blob/kuloodporny-loosehelmet-wip/ACPL_LooseHelmet/functions/Init.sqf

Instead of maintaining list of destroyed items, we should set variable on weapon holder.

**Comment by RomanPL79** [comment]
Has been implemented
