### ISSUE TITLE
ACPL_LooseHelmet: Use dynamically obtained position and direction rather than hardcoded positions depending on stance

### ISSUE THREAD

**Issue by kuloodporny** [RomanPL79/ACPL_MM_Systems#8]
https://github.com/RomanPL79/ACPL_MM_Systems/blob/master/ACPL_LooseHelmet/functions/fn_DropHelmet.sqf
Can probably use eyePos, eyeDirection for helmet
Can probably use weaponDirection,, selectionPosition such as "weapon" or similar for primary weapon

**Comment by RomanPL79** [comment]
Dynamically obtained position has been implemented, attach positions for weaponhandlers also has been improved.
