### ISSUE TITLE
ACPL_MM: Use alternative syntax for createVehicle

### ISSUE THREAD

**Issue by kuloodporny** [RomanPL79/ACPL_MM_Systems#9]
`createVehicle [_type, _position, [], 0, "CAN_COLLIDE"]`
With such syntax creation of logics and other items is much faster, as it does not scan the position for possible collisions. Item can then be placed under ground or directly at desired position.

**Comment by RomanPL79** [comment]
Has been implemented in BETA-31 for LooseHelmet
